### ISSUE TITLE
Estimation du temps pour l'intranet

### ISSUE THREAD

**Issue by liZe** [Kozea/adop#16]
À proposer suite à la proposition d'Alexie fin octobre.

**Comment by liZe** [comment]
La demande concerne l'utilisation des outils de Google.

**Comment by yobuntu** [comment]
si on part sur un compte par région et une version simplifée du CDC: les documents sont visibls directement sur google docs (sans l'intégration au site)

10 min pour la création de 2 compte google (admin et rhone-alpes) .
1 jours de dev pour créer les pages (lien vers les documents)
1 jours pour créer les models de documents et l’arborescence
