### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by liZe** [Kozea/adop#3]
Le site est accessible sur http://adop.kozea.fr/

Les couleurs (CMJN et RVB) :
- Gris (26 19 28 0) `#bfbfb3`
- Vert foncé (88 36 100 30) `#1b9832`
- Vert clair (56 5 64 0) `#79bb82`

Contact : Alexie Fournier 07 68 33 16 56 ou adop.contact@gmail.com

Tract : [201512101659.pdf](https://github.com/Kozea/adop/files/58318/201512101659.pdf)

Carte de visite : [201512101700.pdf](https://github.com/Kozea/adop/files/58319/201512101700.pdf)

**Comment by annabellou** [comment]
Fait, à voir si cela convient !

**Comment by liZe** [comment]
J'ai mis en production sur adop.kozea.fr

@LaurenceBrandicourt tu penses que ça va leur plaire ?

**Comment by annabellou** [comment]
Retours de Miranda : 
- rajouter le logo,
- essayer de mettre les stries vertes comme sur la brochure / carte de visite

**Comment by LaurenceBrandicourt** [comment]
elle t'en remercie !

2015-12-14 17:07 GMT+01:00 annabellou notifications@github.com:

> Retours de Miranda :
> - rajouter le logo,
> - essayer de mettre les stries vertes comme sur la brochure / carte de
>   visite
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Kozea/adop/issues/3#issuecomment-164477491.

## 

_Laurence BRANDICOURT_
Responsable de la Relation Client
t : +33 4 27 11 83 95 <%2B33%200%20820%2090%2010%2026>
f : +33 4 27 11 83 98

**Comment by annabellou** [comment]
J'ai fait les modifs, du coup re-mise en prod plus une nouvelle validation !
@liZe @LaurenceBrandicourt

**Comment by liZe** [comment]
C'est en production !

**Comment by LaurenceBrandicourt** [comment]
j'y vais par le lien adop.kozea.fr ? je retombe sur l'ancienne version...

2015-12-16 11:24 GMT+01:00 Guillaume Ayoub notifications@github.com:

> C'est en production !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Kozea/adop/issues/3#issuecomment-165058280.

## 

_Laurence BRANDICOURT_
Responsable de la Relation Client
t : +33 4 27 11 83 95 <%2B33%200%20820%2090%2010%2026>
f : +33 4 27 11 83 98

**Comment by liZe** [comment]
Oui, c'est bien la nouvelle version sur adop.kozea.fr, recharge ta page.

**Comment by LaurenceBrandicourt** [comment]
Bravo c'est trop bien Annabelle !

Le 16 décembre 2015 à 11:27, Guillaume Ayoub notifications@github.com a
écrit :

> Oui, c'est bien la nouvelle version sur adop.kozea.fr, recharge ta page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Kozea/adop/issues/3#issuecomment-165058857.

## 

_Laurence BRANDICOURT_
Responsable de la Relation Client
t : +33 4 27 11 83 95 <%2B33%200%20820%2090%2010%2026>
f : +33 4 27 11 83 98

**Comment by annabellou** [comment]
Ça vend tellement du rêve, je peux comprendre !

**Comment by LaurenceBrandicourt** [comment]
maquette envoyée à Alexie Fournier et Didier Vieilly. 
Dans l'attente de leur retour + codes pour leur nom de domaine + leaflet et charte éthique à télécharger sur leur site
