### ISSUE TITLE
Rédiger et proposer l'offre

### ISSUE THREAD

**Issue by liZe** [Kozea/adop#6]
Le chiffrage a été effectué dans #5.

**Comment by clemenceprem** [comment]
https://docs.google.com/a/kozea.fr/document/d/1QcO8teQU1GabMwi9kNSHzo8r9vzgXNb-bLIJX4EWUIM/edit?usp=sharing

Il me manque le prix non défini par @liZe pour l'étape 2.

**Comment by liZe** [comment]
Ce n'est pas la peine de mettre l'étape 2 sur le devis, on ne sait pas exactement ce qu'ils veulent, et on ne leur fera de toute façon pas avant d'avoir fait l'étape 1.

Des gros bisous à vous (avec ma bouche pleine de sushis et de rāmen) !

**Comment by clemenceprem** [comment]
Profites de tes vacances ! fous nous la paix ! ;-)))

## 

Clémence Prémillieu
Responsable Marketing
KOZEA
1 rue Baumer
69120 VAULX-EN-VELIN
04 27 11 81 37www.kozea.fr

Le 19 avril 2016 à 16:31, Guillaume Ayoub notifications@github.com a
écrit :

**Comment by liZe** [comment]
Devis mis à jour :

https://docs.google.com/a/kozea.fr/document/d/1rZ_oo8TQ7g6P8eegBUWnn_3CgMfnvSpS9u2C84k6ILA/edit?usp=sharing
